Show command to change topic name on readme
ros2/teleop_twist_keyboard pull request #27
Opened 2023-10-29 10:24 UTC by asukiaaa

I want to you to show command to change topic name like teleop_twist_keyboard of ros1.
https://github.com/ros-teleop/teleop_twist_keyboard

Thank you.

2023-10-30 21:47 UTC, clalancette requested changes

2023-10-30 21:47 UTC, clalancette commented on README.md
>  ## Launch
```suggestion
## Run
```

2023-10-30 21:47 UTC, clalancette commented on README.md
> +Run.
```suggestion
```

2023-10-30 21:47 UTC, clalancette commented on README.md
> +Publishing to a different topic (in this case my_cmd_vel).
```suggestion
Publishing to a different topic (in this case `my_cmd_vel`).
```

2023-10-30 22:09 UTC, asukiaaa commented
Thank you for the comment.
I updated so.

2023-10-31 01:22 UTC, clalancette approved these changes
Thanks for the update!

2023-10-31 01:22 UTC, merged